//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class file_info
    {
        public int file_id { get; set; }
        public int folder_id { get; set; }
        public string file_name { get; set; }
        public string is_filepath { get; set; }
        public Nullable<double> capacity { get; set; }
        public bool is_public { get; set; }
        public int is_order { get; set; }
        public bool is_image { get; set; }
        public string keywords { get; set; }
        public bool status { get; set; }
        public Nullable<int> views { get; set; }
        public Nullable<int> download { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
    
        public virtual file_folder file_folder { get; set; }
    }
}
