//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<api_category> api_category { get; set; }
        public virtual DbSet<api_col> api_col { get; set; }
        public virtual DbSet<api_parameters> api_parameters { get; set; }
        public virtual DbSet<api_project> api_project { get; set; }
        public virtual DbSet<api_service> api_service { get; set; }
        public virtual DbSet<api_table> api_table { get; set; }
        public virtual DbSet<ca_places> ca_places { get; set; }
        public virtual DbSet<ca_positions> ca_positions { get; set; }
        public virtual DbSet<cms_lang> cms_lang { get; set; }
        public virtual DbSet<cms_logs> cms_logs { get; set; }
        public virtual DbSet<cms_news> cms_news { get; set; }
        public virtual DbSet<cms_news_users> cms_news_users { get; set; }
        public virtual DbSet<cms_slideshow> cms_slideshow { get; set; }
        public virtual DbSet<cms_slideshow_image> cms_slideshow_image { get; set; }
        public virtual DbSet<cms_topic> cms_topic { get; set; }
        public virtual DbSet<cms_topic_flag> cms_topic_flag { get; set; }
        public virtual DbSet<doc_ca_dispatch_books> doc_ca_dispatch_books { get; set; }
        public virtual DbSet<doc_ca_email_groups> doc_ca_email_groups { get; set; }
        public virtual DbSet<doc_ca_emails> doc_ca_emails { get; set; }
        public virtual DbSet<doc_ca_fields> doc_ca_fields { get; set; }
        public virtual DbSet<doc_ca_groups> doc_ca_groups { get; set; }
        public virtual DbSet<doc_ca_issue_places> doc_ca_issue_places { get; set; }
        public virtual DbSet<doc_ca_positions> doc_ca_positions { get; set; }
        public virtual DbSet<doc_ca_receive_places> doc_ca_receive_places { get; set; }
        public virtual DbSet<doc_ca_security> doc_ca_security { get; set; }
        public virtual DbSet<doc_ca_send_ways> doc_ca_send_ways { get; set; }
        public virtual DbSet<doc_ca_signers> doc_ca_signers { get; set; }
        public virtual DbSet<doc_ca_stamps> doc_ca_stamps { get; set; }
        public virtual DbSet<doc_ca_status> doc_ca_status { get; set; }
        public virtual DbSet<doc_ca_tags> doc_ca_tags { get; set; }
        public virtual DbSet<doc_ca_types> doc_ca_types { get; set; }
        public virtual DbSet<doc_ca_urgency> doc_ca_urgency { get; set; }
        public virtual DbSet<doc_codes> doc_codes { get; set; }
        public virtual DbSet<doc_completed_confirms> doc_completed_confirms { get; set; }
        public virtual DbSet<doc_decision_form_views> doc_decision_form_views { get; set; }
        public virtual DbSet<doc_decision_forms> doc_decision_forms { get; set; }
        public virtual DbSet<doc_email_sent> doc_email_sent { get; set; }
        public virtual DbSet<doc_file_search> doc_file_search { get; set; }
        public virtual DbSet<doc_files> doc_files { get; set; }
        public virtual DbSet<doc_follows> doc_follows { get; set; }
        public virtual DbSet<doc_logs> doc_logs { get; set; }
        public virtual DbSet<doc_master> doc_master { get; set; }
        public virtual DbSet<doc_sign_approval> doc_sign_approval { get; set; }
        public virtual DbSet<doc_tags> doc_tags { get; set; }
        public virtual DbSet<doc_title_docs> doc_title_docs { get; set; }
        public virtual DbSet<doc_title_users> doc_title_users { get; set; }
        public virtual DbSet<doc_titles> doc_titles { get; set; }
        public virtual DbSet<doc_views> doc_views { get; set; }
        public virtual DbSet<doc_workflow_groups> doc_workflow_groups { get; set; }
        public virtual DbSet<doc_workflows> doc_workflows { get; set; }
        public virtual DbSet<file_folder> file_folder { get; set; }
        public virtual DbSet<file_info> file_info { get; set; }
        public virtual DbSet<file_log> file_log { get; set; }
        public virtual DbSet<file_share> file_share { get; set; }
        public virtual DbSet<sql_log> sql_log { get; set; }
        public virtual DbSet<sys_app_menus> sys_app_menus { get; set; }
        public virtual DbSet<sys_fire_base> sys_fire_base { get; set; }
        public virtual DbSet<sys_group> sys_group { get; set; }
        public virtual DbSet<sys_group_type> sys_group_type { get; set; }
        public virtual DbSet<sys_group_users> sys_group_users { get; set; }
        public virtual DbSet<sys_logs> sys_logs { get; set; }
        public virtual DbSet<sys_modules> sys_modules { get; set; }
        public virtual DbSet<sys_organization> sys_organization { get; set; }
        public virtual DbSet<sys_organization_app_menus> sys_organization_app_menus { get; set; }
        public virtual DbSet<sys_organization_config_group> sys_organization_config_group { get; set; }
        public virtual DbSet<sys_role_modules> sys_role_modules { get; set; }
        public virtual DbSet<sys_roles> sys_roles { get; set; }
        public virtual DbSet<sys_sendhub> sys_sendhub { get; set; }
        public virtual DbSet<sys_table_des> sys_table_des { get; set; }
        public virtual DbSet<sys_tables> sys_tables { get; set; }
        public virtual DbSet<sys_token> sys_token { get; set; }
        public virtual DbSet<sys_users> sys_users { get; set; }
        public virtual DbSet<sys_web_acess> sys_web_acess { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<test_case> test_case { get; set; }
        public virtual DbSet<test_step> test_step { get; set; }
        public virtual DbSet<test_times> test_times { get; set; }
        public virtual DbSet<trace> traces { get; set; }
        public virtual DbSet<api_plugin> api_plugin { get; set; }
    
        public virtual ObjectResult<sys_modules_listuser_Result> sys_modules_listuser(string user_id)
        {
            var user_idParameter = user_id != null ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sys_modules_listuser_Result>("sys_modules_listuser", user_idParameter);
        }
    }
}
