//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_organization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sys_organization()
        {
            this.doc_codes = new HashSet<doc_codes>();
            this.doc_decision_forms = new HashSet<doc_decision_forms>();
            this.sys_modules = new HashSet<sys_modules>();
        }
    
        public int organization_id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string organization_name { get; set; }
        public string logo { get; set; }
        public string background_image { get; set; }
        public string is_url { get; set; }
        public Nullable<int> is_order { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> organization_type { get; set; }
        public string text_color { get; set; }
        public string background_color { get; set; }
        public string short_name { get; set; }
        public string address { get; set; }
        public Nullable<double> coord_x { get; set; }
        public Nullable<double> coord_y { get; set; }
        public Nullable<int> place_id { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_ip { get; set; }
        public string created_token_id { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string modified_token_id { get; set; }
        public string modified_ip { get; set; }
        public string api_link { get; set; }
        public string file_link { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_codes> doc_codes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_decision_forms> doc_decision_forms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sys_modules> sys_modules { get; set; }
    }
}
